// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';


function turnLayerOn(name) {
  return /* record */[
          /* name */"LAYER",
          /* options : :: */[
            /* record */[
              /* name */"ON",
              /* value */name
            ],
            /* :: */[
              /* record */[
                /* name */"THAW",
                /* value */name
              ],
              /* [] */0
            ]
          ],
          /* nonDialog : true */1,
          /* newLineAtEnd : true */1
        ];
}

function turnLayerOff(name) {
  return /* record */[
          /* name */"LAYER",
          /* options : :: */[
            /* record */[
              /* name */"OFF",
              /* value */name
            ],
            /* :: */[
              /* record */[
                /* name */"FREEZE",
                /* value */name
              ],
              /* [] */0
            ]
          ],
          /* nonDialog : true */1,
          /* newLineAtEnd : true */1
        ];
}

function toggleLayerVisibility(name, visible) {
  if (visible !== 0) {
    return turnLayerOn(name);
  } else {
    return turnLayerOff(name);
  }
}

exports.turnLayerOn           = turnLayerOn;
exports.turnLayerOff          = turnLayerOff;
exports.toggleLayerVisibility = toggleLayerVisibility;
/* No side effect */
