// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';


console.log("this is reason");

console.log("this is reason");

var x = ( 'here is a string from javascript' );

console.log(x + " back in reason land");

exports.x = x;
/*  Not a pure module */
