// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function buildOption(option) {
  return "_" + (option[/* name */0] + (" " + (option[/* value */1] + "\n")));
}

function buildCommand(command) {
  var str = command[/* nonDialog */2] ? "_.-" : "_.";
  var str$1 = str + (command[/* name */0] + " ");
  var str$2 = List.fold_left((function (acc, option) {
          return acc + buildOption(option);
        }), str$1, command[/* options */1]);
  if (command[/* newLineAtEnd */3]) {
    return str$2 + "\n\n";
  } else {
    return str$2;
  }
}

exports.buildOption  = buildOption;
exports.buildCommand = buildCommand;
/* No side effect */
